### ISSUE TITLE
TypeError: Cannot add property hash, object is not extensible

### ISSUE THREAD

**Issue by dusanmsk** [alladdin/node-lox-mqtt-gateway#14]
Hi, I am getting

TypeError: Cannot add property hash, object is not extensible
    at Object.connect (/tmp/nodelox/node_modules/mqtt/lib/connect/index.js:68:15)
    at Object.mqtt_builder (/tmp/nodelox/lib/mqtt_builder.js:4:23)
    at Object.<anonymous> (/tmp/nodelox/bin/lox-mqtt-gateway.js:15:36)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

when running in alpine docker container, nodejs v12.18.4. Current master @ a6036ca25e85bec3f66468af6aced2a289f94a6b

**Comment by dusanmsk** [comment]
Seems that this is caused by using outdated code on pretty new mqtt lib (package.json tells >=1.7.0 but it uses version 4.x.x). I tried this and it works now. But it is not the best solution :(

https://github.com/dusanmsk/node-lox-mqtt-gateway/commit/fa8221a840d948cfe583a714cc1a89c5cca960b0
