### ISSUE TITLE
Unknown WindowMonitor type of control

### ISSUE THREAD

**Issue by ludekvodicka** [alladdin/node-lox-mqtt-gateway#2]
It seems that latest Loxone control "WindowMonitor" isn;t supported by your tool. It's currently not big deal for me because I used it only for testing. 

```
2017-01-08T16:15:52.981Z - debug: WebSocketAPI - get structure file 2017-01-08 20:33:12
/usr/local/lib/node_modules/node-lox-mqtt-gateway/node_modules/node-lox-structure-file/lib/Factory.js:74
        throw new Error("Invalid type of control '"+value.type+"'");
        ^

Error: Invalid type of control 'WindowMonitor'
    at Factory._create_control (/usr/local/lib/node_modules/node-lox-mqtt-gateway/node_modules/node-lox-structure-file/lib/Factory.js:74:15)
    at Factory.<anonymous> (/usr/local/lib/node_modules/node-lox-mqtt-gateway/node_modules/node-lox-structure-file/lib/Factory.js:54:25)
    at Factory.<anonymous> (/usr/local/lib/node_modules/node-lox-mqtt-gateway/node_modules/node-lox-structure-file/lib/Factory.js:83:35)
    at Array.forEach (native)
    at Factory._map_list (/usr/local/lib/node_modules/node-lox-mqtt-gateway/node_modules/node-lox-structure-file/lib/Factory.js:82:23)
    at Factory.create_from_json (/usr/local/lib/node_modules/node-lox-mqtt-gateway/node_modules/node-lox-structure-file/lib/Factory.js:53:41)
    at Object.create_from_json (/usr/local/lib/node_modules/node-lox-mqtt-gateway/node_modules/node-lox-structure-file/lib/Factory.js:92:24)
    at API.<anonymous> (/usr/local/lib/node_modules/node-lox-mqtt-gateway/bin/lox-mqtt-gateway.js:36:80)
    at emitOne (events.js:101:20)
    at API.emit (events.js:188:7)
```

**Comment by alladdin** [comment]
I'll try to gather structure of WindowMonitor, because it's not documented yet

**Comment by tgurr** [comment]
Looks like the structure file might have been updated with mentions of the WindowsMonitor:
https://www.loxone.com/enen/wp-content/uploads/sites/3/2016/10/0803_StructureFile.pdf under "Structure changes in 8.3 - WindowsMonitor" in case that actually is the info you were missing.

**Comment by alladdin** [comment]
Added in version 3.4
